ci: add release validation step to docker workflow
Adds the validation step from the release workflow to the Docker
workflow to ensure that tags match as expected.

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -37,6 +37,19 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
+          fetch-depth: 0
+
+      - name: Validate release tag ${{ env.RELEASE_VERSION }}
+        run: |
+          expected_tag=$(./scripts/get-git-tag-name.sh version.go)
+          actual_tag=${{ env.RELEASE_VERSION }}
+
+          if [ "$actual_tag" = "$expected_tag" ]; then
+            echo "git tag matches version.go: $actual_tag"
+          else
+            echo "Error: Versions are not equal. Actual: $actual_tag, Expected: $expected_tag"
+            exit 1
+          fi
 
       - name: Build and push default image
         id: docker_build
