.github/workflows: validate release tag version string
This commit adds a check to this project's GitHub release workflow to
ensure that the release version string is SemVer compliant. It also
indirectly ensures that the version string matches the tag that would
have been created with the `make release-tag` command.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -22,13 +22,25 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Set env
+        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+
+      - name: Validate release tag ${{ env.RELEASE_VERSION }}
+        run: |
+          expected_tag=$(./scripts/get-git-tag-name.sh version.go)
+          actual_tag=${{ env.RELEASE_VERSION }}
+          
+          if [ "$actual_tag" = "$expected_tag" ]; then
+            echo "Git tag release string is as expected."
+          else
+            echo "Error: Versions are not equal. Actual: $actual_tag, Expected: $expected_tag"
+            exit 1
+          fi
+
       - name: setup go ${{ env.GO_VERSION }}
         uses: actions/setup-go@v2
         with:
           go-version: '${{ env.GO_VERSION }}'
-
-      - name: Set env
-        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
       - name: build release for all architectures
         run: SKIP_VERSION_CHECK=1 make release tag=${{ env.RELEASE_VERSION }}
